name: dartrun
description: A script runner for Dart with embedded manifests
version: 1.0.0
homepage: https://github.com/kingwill101/drun
funding:
  - https://www.buymeacoffee.com/kingwill101

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  artisanal: ^0.1.0
  crypto: ^3.0.3
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0